# Generated by Django 5.1.3 on 2024-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
