# Generated by Django 5.1.3 on 2024-11-10 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='generated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
